docker-compose-yaml: docker-compose.yml

project: drupal-active-standby-example

tasks:
  post-rollout:
    - run:
        name: IF no Drupal installed drush si with no email sending
        command: |
            if ! drush status --fields=bootstrap | grep -q "Successful"; then
                # no drupal installed, we install drupal from scratch
                drush si config_installer -y --account-name=admin --account-pass=admin install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
            fi
        service: cli
        shell: bash
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

production_routes:
  active:
    routes:
      - nginx:
        - "drupal-as-demo.au.amazee.io":
            tls-acme: true
        - "drupal-as-demo-active.au.amazee.io":
            tls-acme: true
  standby:
    routes:
      - nginx:
        - "drupal-as-demo-standby.au.amazee.io":
            tls-acme: true

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
